# Generated by Django 4.1.7 on 2023-03-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="author_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
